// Last-layer algorithm data shared by the Alg Trainer and Smart Cube pages.
// Algorithms below were checked with a cube simulator: each one keeps the first two layers
// solved, and each case matches its standard number/name.

export const OLL_GROUPS = [
    ["Cross (OCLL)", [21, 22, 23, 24, 25, 26, 27]],
    ["Dot", [1, 2, 3, 4, 17, 18, 19, 20]],
    ["Corners oriented", [28, 57]],
    ["Line (I shape)", [51, 52, 55, 56]],
    ["T shape", [33, 45]],
    ["P shape", [31, 32, 43, 44]],
    ["C shape", [34, 46]],
    ["W shape", [36, 38]],
    ["Square", [5, 6]],
    ["Small L", [47, 48, 49, 50, 53, 54]],
    ["Fish", [9, 10, 35, 37]],
    ["Knight move", [13, 14, 15, 16]],
    ["Small lightning bolt", [7, 8, 11, 12]],
    ["Big lightning bolt", [39, 40]],
    ["Awkward", [29, 30, 41, 42]],
];

export const OLL_ALGS = {
    1: "R U2 R2 F R F' U2 R' F R F'",
    2: "F R U R' U' F' f R U R' U' f'",
    3: "f R U R' U' f' U' F R U R' U' F'",
    4: "f R U R' U' f' U F R U R' U' F'",
    5: "r' U2 R U R' U r",
    6: "r U2 R' U' R U' r'",
    7: "r U R' U R U2 r'",
    8: "r' U' R U' R' U2 r",
    9: "R U R' U' R' F R2 U R' U' F'",
    10: "R U R' U R' F R F' R U2 R'",
    11: "r U R' U R' F R F' R U2 r'",
    12: "M' R' U' R U' R' U2 R U' R r'",
    13: "F U R U' R2 F' R U R U' R'",
    14: "R' F R U R' F' R F U' F'",
    15: "r' U' r R' U' R U r' U r",
    16: "r U r' R U R' U' r U' r'",
    17: "R U R' U R' F R F' U2 R' F R F'",
    18: "r U R' U R U2 r2 U' R U' R' U2 r",
    19: "M U R U R' U' M' R' F R F'",
    20: "r U R' U' M2 U R U' R' U' M'",
    21: "R U2 R' U' R U R' U' R U' R'",
    22: "R U2 R2 U' R2 U' R2 U2 R",
    23: "R2 D' R U2 R' D R U2 R",
    24: "r U R' U' r' F R F'",
    25: "F' r U R' U' r' F R",
    26: "R U2 R' U' R U' R'",
    27: "R U R' U R U2 R'",
    28: "r U R' U' M U R U' R'",
    29: "R U R' U' R U' R' F' U' F R U R'",
    30: "F R' F R2 U' R' U' R U R' F2",
    31: "R' U' F U R U' R' F' R",
    32: "L U F' U' L' U L F L'",
    33: "R U R' U' R' F R F'",
    34: "R U R2 U' R' F R U R U' F'",
    35: "R U2 R2 F R F' R U2 R'",
    36: "L' U' L U' L' U L U L F' L' F",
    37: "F R' F' R U R U' R'",
    38: "R U R' U R U' R' U' R' F R F'",
    39: "L F' L' U' L U F U' L'",
    40: "R' F R U R' U' F' U R",
    41: "R U R' U R U2 R' F R U R' U' F'",
    42: "R' U' R U' R' U2 R F R U R' U' F'",
    43: "R' U' F' U F R",
    44: "f R U R' U' f'",
    45: "F R U R' U' F'",
    46: "R' U' R' F R F' U R",
    47: "R' U' R' F R F' R' F R F' U R",
    48: "F R U R' U' R U R' U' F'",
    49: "r U' r2 U r2 U r2 U' r",
    50: "r' U r2 U' r2 U' r2 U r'",
    51: "F U R U' R' U R U' R' F'",
    52: "R U R' U R U' B U' B' R'",
    53: "r' U' R U' R' U R U' R' U2 r",
    54: "r U R' U R U' R' U R U2 r'",
    55: "R' F R U R U' R2 F' R2 U' R' U R U R'",
    56: "r' U' r U' R' U R U' R' U R r' U r",
    57: "R U R' U' M' U R U' r'",
};

// Nicknames for the cases most people learn first.
export const OLL_NICKNAMES = {
    21: "H", 22: "Pi", 23: "Headlights", 24: "Chameleon", 25: "Bowtie", 26: "Anti-Sune", 27: "Sune",
    33: "T shape", 45: "T shape", 57: "H (corners oriented)",
};

export const PLL_GROUPS = [
    ["Edges only", ["Ua", "Ub", "H", "Z"]],
    ["Corners only", ["Aa", "Ab", "E"]],
    ["Adjacent corner swap", ["T", "F", "Ja", "Jb", "Ra", "Rb"]],
    ["G perms", ["Ga", "Gb", "Gc", "Gd"]],
    ["Diagonal corner swap", ["V", "Y", "Na", "Nb"]],
];

export const PLL_ALGS = {
    Aa: "x R' U R' D2 R U' R' D2 R2 x'",
    Ab: "x R2 D2 R U R' D2 R U' R x'",
    E: "x' R U' R' D R U R' D' R U R' D R U' R' D' x",
    F: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R",
    Ga: "R2 U R' U R' U' R U' R2 U' D R' U R D'",
    Gb: "R' U' R U D' R2 U R' U R U' R U' R2 D",
    Gc: "R2 U' R U' R U R' U R2 U D' R U' R' D",
    Gd: "R U R' U' D R2 U' R U' R' U R' U R2 D'",
    H: "M2 U M2 U2 M2 U M2",
    Ja: "R' U L' U2 R U' R' U2 R L",
    Jb: "R U R' F' R U R' U' R' F R2 U' R'",
    Na: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'",
    Nb: "R' U R U' R' F' U' F R U R' F R' F' R U' R",
    Ra: "R U' R' U' R U R D R' U' R D' R' U2 R'",
    Rb: "R2 F R U R U' R' F' R U2 R' U2 R",
    T: "R U R' U' R' F R2 U' R' U' R U R' F'",
    Ua: "M2 U M U2 M' U M2",
    Ub: "M2 U' M U2 M' U' M2",
    V: "R U' R U R' D R D' R U' D R2 U R2 D' R2",
    Y: "F R U' R' U' R U R' F' R U R' U' R' F R F'",
    Z: "M' U M2 U M2 U M' U2 M2",
};
